name: neural_structural_opt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.23.5,<2.0.0
  - scipy>=1.10.0
  - scikit-image>=0.20.0
  - pillow>=9.0.0
  - xarray>=2023.1.0
  - pandas>=1.5.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - tqdm>=4.64.0
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - torchaudio>=2.0.0
    - autograd>=1.8.0
    - nlopt>=2.7.0
    - scikit-sparse>=0.4.0
    - apache-beam>=2.40.0
    - absl-py>=1.0.0
    - ftfy>=6.0.0
    - regex>=2021.0.0
    - kornia>=0.6.0
    - open-clip-torch>=2.20.0
    - git+https://github.com/openai/CLIP.git
